# Generated by Django 3.1.7 on 2021-03-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_tool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='portfolio_id',
            new_name='portfolio',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='user_id',
            new_name='user',
        ),
    ]
