# Generated by Django 3.1.7 on 2021-03-24 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_tool', '0005_portfolio_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance_history',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
