# Generated by Django 3.1.7 on 2021-03-29 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_tool', '0007_auto_20210324_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='purchase_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
