# Generated by Django 3.1.7 on 2021-03-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user_id',
            new_name='user',
        ),
    ]
