# Generated by Django 3.1.7 on 2021-03-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tool', '0002_auto_20210329_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
