# Generated by Django 3.1.7 on 2021-04-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monteresults',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
